import fs from 'node:fs/promises';
import path from 'node:path';
import type { OutlineCard } from './parse-gamma';
import type { ArchetypeName, TimelineCard, ManifestEntry } from '../dalio/types';

export function mapCardToArchetype(card: OutlineCard): ArchetypeName {
  if (card.index === 0) return 'TitleSpotlight';
  const text = (card.title + ' ' + card.body).toLowerCase();
  if (/对比|vs|两|比较/.test(text)) return 'Comparison';
  if (/月度|趋势|时序|增长|下降/.test(text)) return 'TimeSeries';
  if (/循环|机器|引擎|齿轮/.test(text)) return 'Cycle';
  if (/流向|因果|→|导致|引起/.test(text)) return 'CauseEffect';
  if (/层级|树|分布|结构/.test(text)) return 'Hierarchy';
  if (/放大|聚焦|从.+到/.test(text)) return 'MacroMicroZoom';
  return 'ConceptReveal';
}

export function buildTimeline(
  outline: OutlineCard[], manifest: ManifestEntry[], fps = 30,
): TimelineCard[] {
  return outline.map((card) => {
    const m = manifest.find((x) => x.index === card.index);
    const audioFrames = m ? Math.ceil((m.durationMs / 1000) * fps) : 90;
    const durationFrames = audioFrames + Math.ceil(1.5 * fps); // 1.5s post-roll
    return {
      index: card.index, archetype: mapCardToArchetype(card),
      title: card.title, body: card.body, narration: card.narration,
      durationFrames, audioPath: m?.mp3,
    };
  });
}

export async function generateTimeline(
  cards: TimelineCard[],
  audioBaseUrl: string,
  outputPath: string,
): Promise<void> {
  const imports = [
    `import React from 'react';`,
    `import { Series } from 'remotion';`,
    `import { TitleSpotlight } from '../dalio/components/TitleSpotlight';`,
    `import { ConceptReveal } from '../dalio/archetypes/ConceptReveal';`,
    `import { CauseEffect } from '../dalio/archetypes/CauseEffect';`,
    `import { Comparison } from '../dalio/archetypes/Comparison';`,
    `import { Cycle } from '../dalio/archetypes/Cycle';`,
    `import { TimeSeries } from '../dalio/archetypes/TimeSeries';`,
    `import { Hierarchy } from '../dalio/archetypes/Hierarchy';`,
    `import { MacroMicroZoom } from '../dalio/archetypes/MacroMicroZoom';`,
    `import { NarrationCue } from '../dalio/components/NarrationCue';`,
  ].join('\n');

  const manifest = cards.map((c) => ({
    index: c.index,
    mp3: c.audioPath ?? '',
    durationMs: Math.round((c.durationFrames / 30) * 1000),
    narration: c.narration,
  }));

  const seriesItems = cards.map((card) => {
    const cardJson = JSON.stringify({ index: card.index, title: card.title, body: card.body, narration: card.narration, rawHtml: '' });
    let component: string;
    if (card.archetype === 'TitleSpotlight') {
      component = `<TitleSpotlight title={${JSON.stringify(card.title)}} />`;
    } else {
      component = `<${card.archetype} card={${cardJson}} />`;
    }
    return `    <Series.Sequence durationInFrames={${card.durationFrames}}>\n      ${component}\n    </Series.Sequence>`;
  }).join('\n');

  const manifestJson = JSON.stringify(manifest, null, 2);

  const code = `// Auto-generated by build-timeline.ts — DO NOT EDIT
${imports}

const MANIFEST = ${manifestJson};

export const DalioTimeline: React.FC = () => {
  return (
    <>
      <Series>
${seriesItems}
      </Series>
      <NarrationCue manifest={MANIFEST} audioBaseUrl={${JSON.stringify(audioBaseUrl)}} />
    </>
  );
};
`;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, code, 'utf-8');
  console.log(`✓ Generated ${outputPath} — ${cards.length} cards, total ${cards.reduce((s, c) => s + c.durationFrames, 0)} frames`);
}

if (require.main === module) {
  const [, , outlineJson, manifestJson, audioBaseUrl, outputPath] = process.argv;
  if (!outlineJson || !manifestJson || !audioBaseUrl || !outputPath) {
    console.error('Usage: tsx build-timeline.ts <outline.json> <manifest.json> <audio-base> <out.tsx>');
    process.exit(1);
  }
  Promise.all([
    fs.readFile(outlineJson, 'utf-8').then(JSON.parse),
    fs.readFile(manifestJson, 'utf-8').then(JSON.parse),
  ]).then(([outline, manifest]) => {
    const cards = buildTimeline(outline, manifest);
    return generateTimeline(cards, audioBaseUrl, outputPath);
  }).catch((err) => {
    console.error(err);
    process.exit(2);
  });
}
