// Auto-generated by build-timeline.ts — DO NOT EDIT
// Run: npx tsx src/scripts/build-timeline.ts <outline> <manifest> <audio-base> src/dalio/Timeline.generated.tsx
import React from 'react';
import { TitleSpotlight } from './components/TitleSpotlight';

export const DalioTimeline: React.FC = () => {
  return <TitleSpotlight title="Dalio Finance Video" subtitle="Run /finance-video to generate" />;
};
